import 'package:get/get.dart';
import '../utils/constants/text_strings.dart';

class TTextLocalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    ///================================= [[Local English Text]]===============================================///
    'en_US': {
      // App Info
      TTexts.appName: "Daily Mate",
      TTexts.adminEmail: "support@gmail.com",
      TTexts.adminPassword: "Admin@123",
      TTexts.welocmeMessage: "Welcome to",

      // Common
      TTexts.no: "No",
      TTexts.yes: "Yes",
      TTexts.and: "and",
      TTexts.skip: "Skip",
      TTexts.found: "Found",
      TTexts.notFound: "Not Found",
      TTexts.tryAgain: "Try Again",
      TTexts.ok: "OK",
      TTexts.close: "Close",
      TTexts.done: "Done",
      TTexts.submit: "Submit",
      TTexts.tContinue: "Continue",
      TTexts.cancel: "Cancel",
      TTexts.active: "Active",
      TTexts.schedule: "Schedule",
      TTexts.today: "Today",
      TTexts.save: "Save",
      TTexts.tUpdate: "Update",
      TTexts.changePassword: "Change Password",
      TTexts.user: "User",
      TTexts.success: "SUCCESS",
      TTexts.error: "ERROR",

      // Onboarding
      TTexts.onBoardingTitle1: "Choose your product",
      TTexts.onBoardingTitle2: "Select Payment Method",
      TTexts.onBoardingTitle3: "Deliver at your door step",
      TTexts.onBoardingSubTitle1:
          "Welcome to a World of Limitless Choices - Your Perfect Product Awaits!",
      TTexts.onBoardingSubTitle2:
          "For Seamless Transactions, Choose Your Payment Path - Your Convenience, Our Priority!",
      TTexts.onBoardingSubTitle3:
          "From Our Doorstep to Yours - Swift, Secure, and Contactless Delivery!",

      // Home Screen
      TTexts.homeAppbarTitle: "Welcome back!",
      TTexts.goodMorning: "Good Morning",
      TTexts.goodEvening: "Good Evening",
      TTexts.goodAfternoon: "Good Afternoon",
      TTexts.goodNight: "Good Night",
      TTexts.viewAll: "View All",
      TTexts.wearMask: "Wear a Mask",
      TTexts.carryUmbrella: "Carry Umbrella",
      TTexts.humidity: "Humidity",
      TTexts.wind: "Wind",
      TTexts.aqi: "AQI",
      TTexts.pm25: "PM2.5",
      TTexts.pm10: "PM10",
      TTexts.todaysForecast: "Today's Forecast",
      TTexts.nextFiveDays: "Next 5 Days",
      TTexts.tomorrow: "Tomorrow",
      TTexts.visibilty: "Visibility",
      TTexts.quickTools: "Quick Tools",
      TTexts.calculator: "Calculator",
      TTexts.torch: "Torch",
      TTexts.notes: "Notes",
      TTexts.expenses: "Expenses",
      TTexts.converter: "Converter",
      TTexts.steps: "Steps",

      // Calendar Screen
      TTexts.allHolidays: "All Holidays",
      TTexts.addEvent: "Add Event",
      TTexts.editEvent: "Edit Event",

      TTexts.yourEvents: "Your Events",
      TTexts.holidays: "Holidays",

      // Quotes Screen
      TTexts.copy: "Copy",
      TTexts.share: "Share",
      TTexts.streak: "Streak",

      // Settings Screen
      TTexts.language: "Language",
      TTexts.waterReminder: "Water Reminder",
      TTexts.exerciseReminder: "Exercise Reminder",
      TTexts.medicineReminder: "Medicine Reminder",
      TTexts.notification: "Notification",
      TTexts.subscription: "Subscription",
      TTexts.themeMode: "Theme Mode",

      // Bottom Nav
      TTexts.home: "Home",
      TTexts.calendar: "Calendar",
      TTexts.quotes: "Quotes",
      TTexts.settings: "Settings",
      TTexts.notifications: "Notifications",

      // Validation
      TTexts.emptyFieldValidation: "This field is required",

      // Months
      TTexts.january: "January",
      TTexts.february: "February",
      TTexts.march: "March",
      TTexts.april: "April",
      TTexts.may: "May",
      TTexts.june: "June",
      TTexts.july: "July",
      TTexts.august: "August",
      TTexts.september: "September",
      TTexts.october: "October",
      TTexts.november: "November",
      TTexts.december: "December",

      // Days
      TTexts.monday: "Monday",
      TTexts.tuesday: "Tuesday",
      TTexts.wednesday: "Wednesday",
      TTexts.thursday: "Thursday",
      TTexts.friday: "Friday",
      TTexts.saturday: "Saturday",
      TTexts.sunday: "Sunday",

      // Converter
      TTexts.from: "From",
      TTexts.to: "To",
      TTexts.enterValue: "Enter Value",
      TTexts.convert: "Convert",
      TTexts.conversionResult: "Conversion Result",
      TTexts.conversionNotAvailable: "Conversion not available for",
      TTexts.loading: "Loading...",
      TTexts.result: "Result",

      // Steps
      TTexts.totalSteps: "Total Steps",
      TTexts.stepsToday: "Steps Today",
      TTexts.weeklySteps: "Weekly Steps",
      TTexts.monthlySteps: "Monthly Steps",
      TTexts.yearlySteps: "Yearly Steps",
      TTexts.goal: "Goal",
      TTexts.stepHistory: "Step History",
      TTexts.noStepData: "No step data available.",
      TTexts.setYourGoal: "Set your goal",
      TTexts.congrats: "Congratulations!",
      TTexts.youHaveAchievedYourGoal: "You have achieved your goal!",
      TTexts.keepItUp: "Keep it up!",

      // Expenses
      TTexts.addExpense: "Add Expense",
      TTexts.amount: "Amount",
      TTexts.category: "Category",
      TTexts.date: "Date",
      TTexts.note: "Note",
      TTexts.editExpense: "Edit Expense",
      TTexts.deleteExpense: "Delete Expense",
      TTexts.recentExpense: "Recent Expenses",
      TTexts.thisWeek: "This Week",
      TTexts.thisMonth: "This Month",
      TTexts.expenseAdded: "Expense added successfully",
      TTexts.expenseUpdated: "Expense updated successfully",
      TTexts.expenseDeleted: "Expense deleted successfully",
      TTexts.confirmDeleteExpense:
          "Are you sure you want to delete this expense?",
      TTexts.totalExpenses: "Total Expenses",
      TTexts.noExpenses: "No expenses added yet.",
      TTexts.selectDate: "Select Date",
      TTexts.enterAmount: "Enter amount",
      TTexts.enterNote: "Enter note (optional)",
      TTexts.selectCategory: "Select category",
      TTexts.allCategories: "All Categories",
      TTexts.monthlyExpense: "Monthly Expense",
      TTexts.weeklyExpense: "Weekly Expense",
      TTexts.dailyExpense: "Daily Expense",
      TTexts.expenseSummary: "Expense Summary",
      TTexts.noExpenseData: "No expense data available.",
      TTexts.chooseCategory: "Choose Category",
      TTexts.other: "Other",
      TTexts.food: "Food",
      TTexts.transport: "Transport",
      TTexts.shopping: "Shopping",
      TTexts.bills: "Bills",
      TTexts.entertainment: "Entertainment",
      TTexts.health: "Health",
      TTexts.education: "Education",
      TTexts.groceries: "Groceries",
      TTexts.travel: "Travel",
      TTexts.gifts: "Gifts",
      TTexts.subscriptions: "Subscriptions",
      TTexts.personalCare: "Personal Care",
      TTexts.fitness: "Fitness",

      // Notes
      TTexts.addNote: "Add Note",
      TTexts.editNote: "Edit Note",
      TTexts.deleteNote: "Delete Note",
      TTexts.noteAdded: "Note added successfully",
      TTexts.noteUpdated: "Note updated successfully",
      TTexts.noteDeleted: "Note deleted successfully",
      TTexts.confirmDeleteNote: "Are you sure you want to delete this note?",
      TTexts.noNotes: "No notes added yet.",
      TTexts.reset: "Reset",
      TTexts.resetExpenseSubtitle:
          "This will clear all your previous expense data. Are you sure?",
      TTexts.enterNoteTitle: "Enter note title",
      TTexts.enterNoteContent: "Enter note content",
      TTexts.searchNotes: "Search notes...",
      TTexts.lastModified: "Last modified",
      TTexts.pinNote: "Pin Note",
      TTexts.unpinNote: "Unpin Note",
      TTexts.pinnedNotes: "Pinned Notes",
      TTexts.allNotes: "All Notes",
      TTexts.title: "Title (eg. Grocery, Meeting)",
      TTexts.title40Chars: "Title (max 40 chars)",
      TTexts.content: "Content",
      TTexts.noteDetails: "Note Details",
      TTexts.chooseNoteColor: "Choose note color",
      TTexts.noNoteData: "No note data available.",

      // -- Health (Steps & Sleep)
      TTexts.sleepTab: "Sleep",
      TTexts.dailyGoal: "Daily Goal",
      TTexts.keepGoaing: "Keep Going!",
      TTexts.status: "Status",
      TTexts.walking: "Walking",
      TTexts.stopped: "Stopped",
      TTexts.youHaveCompleted: "You've completed",
      TTexts.ofYourGoal: "of your goal",
      TTexts.calories: "Calories",
      TTexts.distance: "Distance",
      TTexts.time: "Time",
      TTexts.km: "km",
      TTexts.min: "min",
      TTexts.kcal: "Kcal",
      TTexts.sleepGoal: "Sleep Goal",
      TTexts.todaySleep: "Today Sleep",
      TTexts.lastNight: "Last Night",
      TTexts.bedtime: "Bedtime",
      TTexts.wakeUp: "Wake Up",
      TTexts.of: "of",
      TTexts.hrs: "hrs",
      TTexts.excellent: "Excellent",
      TTexts.good: "Good",
      TTexts.fair: "Fair",
      TTexts.poor: "Poor",
      TTexts.sleepTrend: "Sleep Trend",
      TTexts.weekly: "Weekly",
      TTexts.weeklyOverview: "Weekly Overview",
      TTexts.sleepAlreadyLogged: "Sleep Already Logged.",
      TTexts.logSleep: "Log Sleep",
      TTexts.almostThere: "Almost There!",
      TTexts.goalAchieved: "🎉 Goal Achieved!",

      // -- Water Reminders
      TTexts.waterDrinkInADay: "How much water do you want to drink in a day?",
      TTexts.waterSetReminder: "What's your usual cup size?",
      TTexts.custom: "Custom",
      TTexts.dailyRoutine: "Daily Routine",
      TTexts.activeReminder: "Active Reminder",
      TTexts.summary: "Summary",

      // -- Medicine Reminders
      TTexts.medicineName: "Medicine Name",

      TTexts.reminderTime: "Reminder Time",

      TTexts.duration: "Duration",

      TTexts.days: "Days",

      TTexts.onlyToday: "Only Today",

      TTexts.selectTime: "Select Time",

      // -- Exercise Reminders
      TTexts.exerciseReminderTitle: "Set Daily Exercise Reminder",
      TTexts.exerciseReminderSubTitle:
          "Pick a time and  get a daily exercise notification to keep your routine on consistent.",
      TTexts.exerciseTime: "Select your exercise reminder time",
      TTexts.quickSelectTime: "Quick Select Time",

      TTexts.nearByLocations: "Nearby\nLocations",
    },

    ///================================= [[Local Hindi Text]]===============================================///
    'hi_IN': {
      // App Info
      TTexts.appName: "डेली मेट",
      TTexts.adminEmail: "support@gmail.com",
      TTexts.adminPassword: "Admin@123",
      TTexts.welocmeMessage: "आपका स्वागत है",

      // Common
      TTexts.no: "नहीं",
      TTexts.yes: "हाँ",
      TTexts.and: "और",
      TTexts.skip: "छोड़ें",
      TTexts.found: "मिला",
      TTexts.notFound: "नहीं मिला",
      TTexts.tryAgain: "फिर से कोशिश करें",
      TTexts.ok: "ठीक है",
      TTexts.close: "बंद करें",
      TTexts.done: "पूरा हुआ",
      TTexts.submit: "जमा करें",
      TTexts.tContinue: "जारी रखें",
      TTexts.cancel: "रद्द करें",
      TTexts.active: "सक्रिय",
      TTexts.schedule: "निर्धारित करें",
      TTexts.today: "आज",
      TTexts.save: "सहेजें",
      TTexts.tUpdate: "अपडेट करें",
      TTexts.changePassword: "पासवर्ड बदलें",
      TTexts.user: "उपयोगकर्ता",
      TTexts.success: "सफलता",
      TTexts.error: "त्रुटि",

      // Onboarding
      TTexts.onBoardingTitle1: "अपना उत्पाद चुनें",
      TTexts.onBoardingTitle2: "भुगतान विधि चुनें",
      TTexts.onBoardingTitle3: "डिलीवरी आपके दरवाजे पर",
      TTexts.onBoardingSubTitle1:
          "असीमित विकल्पों की दुनिया में आपका स्वागत है - आपका परफेक्ट उत्पाद इंतज़ार कर रहा है!",
      TTexts.onBoardingSubTitle2:
          "निर्बाध लेन-देन के लिए, अपनी भुगतान विधि चुनें - आपकी सुविधा, हमारी प्राथमिकता!",
      TTexts.onBoardingSubTitle3:
          "हमारे दरवाजे से आपके दरवाजे तक - तेज़, सुरक्षित और संपर्क रहित डिलीवरी!",

      // Home Screen
      TTexts.homeAppbarTitle: "वापस स्वागत है!",
      TTexts.goodMorning: "सुप्रभात",
      TTexts.goodEvening: "शुभ संध्या",
      TTexts.goodAfternoon: "शुभ दोपहर",
      TTexts.goodNight: "शुभ रात्रि",
      TTexts.viewAll: "सभी देखें",
      TTexts.wearMask: "मास्क पहनें",
      TTexts.carryUmbrella: "छाता साथ रखें",
      TTexts.humidity: "नमी",
      TTexts.wind: "हवा",
      TTexts.aqi: "ए क्यू आई",
      TTexts.pm25: "पीएम 2.5",
      TTexts.pm10: "पीएम 10",
      TTexts.todaysForecast: "आज का पूर्वानुमान",
      TTexts.nextFiveDays: "अगले 5 दिन",
      TTexts.tomorrow: "कल",
      TTexts.visibilty: "दृश्यता",
      TTexts.quickTools: "त्वरित उपकरण",
      TTexts.calculator: "कैलकुलेटर",
      TTexts.torch: "टॉर्च",
      TTexts.notes: "नोट्स",
      TTexts.expenses: "खर्चे",
      TTexts.converter: "कन्वर्टर",
      TTexts.steps: "कदम",

      // Calendar Screen
      TTexts.allHolidays: "सभी छुट्टियां",
      TTexts.addEvent: "ईवेंट जोड़ें",
      TTexts.editEvent: "ईवेंट संपाद",
      TTexts.yourEvents: "आपके ईवेंट्स",
      TTexts.holidays: "छुट्टियां",

      // Quotes Screen
      TTexts.copy: "कॉपी",
      TTexts.share: "शेयर",
      TTexts.streak: "सिलसिला",

      // Settings Screen
      TTexts.language: "भाषा",
      TTexts.waterReminder: "पानी की याद दिलाएं",
      TTexts.exerciseReminder: "व्यायाम की याद दिलाएं",
      TTexts.medicineReminder: "दवा की याद दिलाएं",
      TTexts.notification: "सूचना",
      TTexts.subscription: "सदस्यता",
      TTexts.themeMode: "थीम मोड",

      // Bottom Nav
      TTexts.home: "होम",
      TTexts.calendar: "कैलेंडर",
      TTexts.quotes: "उद्धरण",
      TTexts.settings: "सेटिंग्स",
      TTexts.notifications: "सूचनाएं",

      // Validation
      TTexts.emptyFieldValidation: "यह फ़ील्ड आवश्यक है",

      // Months
      TTexts.january: "जनवरी",
      TTexts.february: "फ़रवरी",
      TTexts.march: "मार्च",
      TTexts.april: "अप्रैल",
      TTexts.may: "मई",
      TTexts.june: "जून",
      TTexts.july: "जुलाई",
      TTexts.august: "अगस्त",
      TTexts.september: "सितंबर",
      TTexts.october: "अक्टूबर",
      TTexts.november: "नवंबर",
      TTexts.december: "दिसंबर",

      // Days
      TTexts.monday: "सोमवार",
      TTexts.tuesday: "मंगलवार",
      TTexts.wednesday: "बुधवार",
      TTexts.thursday: "गुरुवार",
      TTexts.friday: "शुक्रवार",
      TTexts.saturday: "शनिवार",
      TTexts.sunday: "रविवार",

      // Converter
      TTexts.from: "से",
      TTexts.to: "तक",
      TTexts.enterValue: "मान दर्ज करें",
      TTexts.convert: "कन्वर्ट करें",
      TTexts.conversionResult: "परिवर्तन परिणाम",
      TTexts.conversionNotAvailable: "इसके लिए परिवर्तन उपलब्ध नहीं है",
      TTexts.loading: "लोड हो रहा है...",
      TTexts.result: "परिणाम",

      // Steps
      TTexts.totalSteps: "कुल कदम",
      TTexts.stepsToday: "आज के कदम",
      TTexts.weeklySteps: "साप्ताहिक कदम",
      TTexts.monthlySteps: "मासिक कदम",
      TTexts.yearlySteps: "वार्षिक कदम",
      TTexts.goal: "लक्ष्य",
      TTexts.stepHistory: "कदमों का इतिहास",
      TTexts.noStepData: "कोई कदम डेटा उपलब्ध नहीं।",
      TTexts.setYourGoal: "अपना लक्ष्य निर्धारित करें",
      TTexts.congrats: "बधाई हो!",
      TTexts.youHaveAchievedYourGoal: "आपने अपना लक्ष्य प्राप्त कर लिया है!",
      TTexts.keepItUp: "ऐसे ही जारी रखें!",

      // Expenses
      TTexts.addExpense: "खर्च जोड़ें",
      TTexts.amount: "राशि",
      TTexts.category: "श्रेणी",
      TTexts.date: "तारीख",
      TTexts.note: "नोट",
      TTexts.editExpense: "खर्च संपादित करें",
      TTexts.recentExpense: "हाल के खर्चे",
      TTexts.thisWeek: "इस सप्ताह",
      TTexts.thisMonth: "इस महीने",
      TTexts.reset: "रीसेट करें",
      TTexts.noData: "कोई डेटा नहीं",
      TTexts.resetExpenseSubtitle:
          "यह आपके सभी पिछले खर्च डेटा को साफ़ कर देगा। क्या आप सुनिश्चित हैं?",
      TTexts.deleteExpense: "खर्च हटाएँ",
      TTexts.expenseAdded: "खर्च सफलतापूर्वक जोड़ा गया",
      TTexts.expenseUpdated: "खर्च सफलतापूर्वक अपडेट किया गया",
      TTexts.expenseDeleted: "खर्च सफलतापूर्वक हटाया गया",
      TTexts.confirmDeleteExpense: "क्या आप वाकई इस खर्च को हटाना चाहते हैं?",
      TTexts.totalExpenses: "कुल खर्च",
      TTexts.noExpenses: "अभी तक कोई खर्च नहीं जोड़ा गया।",
      TTexts.selectDate: "तारीख चुनें",
      TTexts.enterAmount: "राशि दर्ज करें",
      TTexts.enterNote: "नोट दर्ज करें (वैकल्पिक)",
      TTexts.selectCategory: "श्रेणी चुनें",
      TTexts.allCategories: "सभी श्रेणियाँ",
      TTexts.monthlyExpense: "मासिक खर्च",
      TTexts.weeklyExpense: "साप्ताहिक खर्च",
      TTexts.dailyExpense: "दैनिक खर्च",
      TTexts.expenseSummary: "खर्च सारांश",
      TTexts.noExpenseData: "कोई खर्च डेटा उपलब्ध नहीं।",
      TTexts.chooseCategory: "श्रेणी चुनें",
      TTexts.other: "अन्य",
      TTexts.food: "खाना",
      TTexts.transport: "परिवहन",
      TTexts.shopping: "खरीदारी",
      TTexts.bills: "बिल",
      TTexts.entertainment: "मनोरंजन",
      TTexts.health: "स्वास्थ्य",
      TTexts.education: "शिक्षा",
      TTexts.groceries: "किराने का सामान",
      TTexts.travel: "यात्रा",
      TTexts.gifts: "उपहार",
      TTexts.subscriptions: "सदस्यताएँ",
      TTexts.personalCare: "व्यक्तिगत देखभाल",
      TTexts.fitness: "फ़िटनेस",

      // Notes
      TTexts.addNote: "नोट जोड़ें",
      TTexts.editNote: "नोट संपादित करें",
      TTexts.deleteNote: "नोट हटाएँ",
      TTexts.noteAdded: "नोट सफलतापूर्वक जोड़ा गया",
      TTexts.noteUpdated: "नोट सफलतापूर्वक अपडेट किया गया",
      TTexts.noteDeleted: "नोट सफलतापूर्वक हटाया गया",
      TTexts.confirmDeleteNote: "क्या आप वाकई इस नोट को हटाना चाहते हैं?",
      TTexts.noNotes: "अभी तक कोई नोट नहीं जोड़ा गया।",
      TTexts.enterNoteTitle: "नोट शीर्षक दर्ज करें",
      TTexts.enterNoteContent: "नोट सामग्री दर्ज करें",
      TTexts.searchNotes: "नोट खोजें...",
      TTexts.lastModified: "अंतिम संशोधन",
      TTexts.pinNote: "नोट पिन करें",
      TTexts.unpinNote: "नोट अनपिन करें",
      TTexts.pinnedNotes: "पिन किए गए नोट्स",
      TTexts.allNotes: "सभी नोट्स",
      TTexts.title: "शीर्षक (जैसे. किराना, बैठक)",
      TTexts.title40Chars: "शीर्षक (अधिकतम 40 अक्षर)",
      TTexts.content: "सामग्री",
      TTexts.noteDetails: "नोट विवरण",
      TTexts.chooseNoteColor: "नोट का रंग चुनें",
      TTexts.noNoteData: "कोई नोट डेटा उपलब्ध नहीं।",

      // -- Health (Steps & Sleep)
      TTexts.sleepTab: "नींद",
      TTexts.dailyGoal: "दैनिक लक्ष्य",
      TTexts.keepGoaing: "जारी रखें!",
      TTexts.status: "स्थिति",
      TTexts.walking: "चलना",
      TTexts.stopped: "रुका",
      TTexts.youHaveCompleted: "आपने पूरा किया है",
      TTexts.ofYourGoal: "अपने लक्ष्य का",
      TTexts.calories: "कैलोरी",
      TTexts.distance: "दूरी",
      TTexts.time: "समय",
      TTexts.km: "किमी",
      TTexts.min: "मिनट",
      TTexts.kcal: "किलो कैलोरी",
      TTexts.sleepGoal: "नींद का लक्ष्य",
      TTexts.todaySleep: "आज की नींद",
      TTexts.lastNight: "पिछली रात",
      TTexts.bedtime: "सोने का समय",
      TTexts.wakeUp: "जागने का समय",
      TTexts.of: "में से",
      TTexts.hrs: "घंटे",
      TTexts.excellent: "उत्कृष्ट",
      TTexts.good: "अच्छा",
      TTexts.fair: "ठीक",
      TTexts.poor: "खराब",
      TTexts.sleepTrend: "नींद प्रवृत्ति",
      TTexts.weekly: "साप्ताहिक",
      TTexts.weeklyOverview: "साप्ताहिक अवलोकन",
      TTexts.sleepAlreadyLogged: "नींद पहले से दर्ज है।",
      TTexts.logSleep: "नींद दर्ज करें",
      TTexts.almostThere: "लगभग हो गया!",
      TTexts.goalAchieved: "🎉 लक्ष्य प्राप्त!",

      // -- Water Reminders
      TTexts.waterDrinkInADay: "आप दिन में कितना पानी पीना चाहते हैं?",
      TTexts.waterSetReminder: "आपका सामान्य कप आकार क्या है?",
      TTexts.custom: "कस्टम",
      TTexts.dailyRoutine: "दैनिक दिनचर्या",
      TTexts.activeReminder: "सक्रिय रिमाइंडर",
      TTexts.summary: "सारांश",

      // -- Medicine Reminders
      TTexts.medicineName: "दवा का नाम",
      TTexts.reminderTime: "रिमाइंडर समय",
      TTexts.duration: "अवधि",
      TTexts.days: "दिन",
      TTexts.onlyToday: "केवल आज",
      TTexts.selectTime: "समय चुनें",

      // -- Exercise Reminders
      TTexts.exerciseReminderTitle: "दैनिक व्यायाम रिमाइंडर सेट करें",
      TTexts.exerciseReminderSubTitle:
          "एक समय चुनें और अपना रूटीन नियमित बनाए रखने के लिए दैनिक व्यायाम सूचना प्राप्त करें।",
      TTexts.exerciseTime: "अपना व्यायाम रिमाइंडर समय चुनें",
      TTexts.quickSelectTime: "त्वरित समय चयन",

      TTexts.nearByLocations: "नज़दीकी\nस्थान",

    },
  };
}
